apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "archodex-agent.clusterRoleBindingName" . }}
  labels:
    {{- include "archodex-agent.labels" . | nindent 4 }}
  {{- with .Values.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "archodex-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "archodex-agent.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io